name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    - name: Run a one-line script
      run: npm ci
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
